# Generated by Django 4.2.7 on 2024-01-31 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadingdate', models.DateField()),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('MECHANICAL', 'MECHANICAL'), ('IT', 'IT'), ('NETWORKING', 'NETWORKING'), ('ECE', 'ECE'), ('OTHER', 'OTHER')], default='CSE', max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('notesfile', models.FileField(null=True, upload_to='note')),
                ('filetype', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC/DOCX'), ('CIVIL', 'CIVIL'), ('ppt', 'PPT/WORD'), ('zip', 'ZIP'), ('image', 'IMAGE'), ('OTHER', 'OTHER')], default='pdf', max_length=30)),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Approved')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update', '-created'],
            },
        ),
    ]
