# Generated by Django 4.2.7 on 2024-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_allsubject_alter_notes_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
