# Generated by Django 4.2.7 on 2024-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_notes_uploadingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
