# Generated by Django 4.2.7 on 2024-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notesfile',
            field=models.FileField(null=True, upload_to='contacy'),
        ),
    ]
