# Generated by Django 4.2.7 on 2024-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
